config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'enigmas#index'
  resources :enigmas do
    resources :comments, only: :create
    collection do
      get 'search'
    end
  end
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :enigma
  belongs_to :user
end

app/models/enigma.rb
class Enigma < ApplicationRecord
  validates :text, presence: true
  belongs_to :user
  has_many :comments

  def self.search(search)
    if search != ""
      Enigma.where('text LIKE(?)', "%#{search}%")
    else
      Enigma.all
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :enigmas
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
   comment = Comment.create(comment_params)
   redirect_to "/enigmas/#{comment.enigma.id}"
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, enigma_id: params[:enigma_id])
  end
end

app/controllers/enigmas_controller.rb
class EnigmasController < ApplicationController
  before_action :set_enigma, only: [:edit, :show]
  before_action :move_to_index, except: [:index, :show, :search]
  
  def index
    @enigmas = Enigma.includes(:user).order("created_at DESC")
  end

  def new
    @enigma = Enigma.new
  end

  def create
    binding.pry
    Enigma.create(enigma_params)
  end

  def destroy
    enigma = Enigma.find(params[:id])
    enigma.destroy
  end

  def edit
  end

  def update
    enigma = Enigma.find(params[:id])
    enigma.update(enigma_params)
  end

  def show
    @comment = Comment.new
    @comments = @enigma.comments.includes(:user)
  end

  def search
    @enigmas = Enigma.search(params[:keyword])
  end

  private
  def enigma_params
    params.require(:enigma).permit(:image, :text).merge(user_id: current_user.id)
  end

  def set_enigma
    @enigma = Enigma.find(params[:id])
  end

  def move_to_index
    unless user_signed_in?
      redirect_to action: :index
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    user = User.find(params[:id])
    @nickname = user.nickname
    @enigmas = user.enigmas
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/enigmas_helper.rb
module EnigmasHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/enigmas/_enigma.html.erb
    <div class="content_post" style="background-image: url(<%= enigma.image %>);">
      <div class="more">
        <span><%= image_tag 'arrow_top.png' %></span>
        <ul class="more_list">
          <li>
            <%= link_to '詳細', enigma_path(enigma.id), method: :get %>
          </li>
          <% if user_signed_in? && current_user.id == enigma.user_id %>
            <li>
              <%= link_to '編集', edit_enigma_path(enigma.id), method: :get %>
            </li>
            <li>
              <%= link_to '削除', enigma_path(enigma.id), method: :delete %>
            </li>
          <% end %>
        </ul>
      </div>
      <p><%= enigma.text %></p>
      <span class="name">
        <a href="/users/<%= enigma.user.id %>">
          <span>投稿者</span><%= enigma.user.nickname %>
        </a>
      </span>
    </div>

app/views/enigmas/_form.html.erb
<%= form_with(model: enigma, local: true) do |form| %>
  <%= form.text_field :image, placeholder: "Image Url" %>
  <%= form.text_area :text, placeholder: "text", rows: "10" %>
  <%= form.submit "SEND" %>
<% end %>

app/views/enigmas/create.html.erb
<div class="contents row">
  <div class="success">
    <h3>投稿が完了しました。</h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/enigmas/destroy.html.erb
<div class="contents row">
  <div class="success">
    <h3>削除が完了しました。</h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/enigmas/edit.html.erb
<div class="contents row">
  <div class="container">
    <h3>編集する</h3>
    <%= render partial: "form", locals: { enigma: @enigma } %>
  </div>
</div>

app/views/enigmas/index.html.erb
<div class="contents row">
  <% @enigmas.each do |enigma| %>
    <%= render partial: "enigma", locals: { enigma: enigma } %>
  <% end %>
</div>

app/views/enigmas/new.html.erb
<div class="contents row">
  <div class="container">
    <h3>エンコード</h3>
    <%= render partial: "form", locals: { enigma: @enigma } %>
  </div>
</div>

app/views/enigmas/search.html.erb
<%= form_with(url: search_enigmas_path, local: true, method: :get, class: "search-form") do |form| %>
  <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
  <%= form.submit "検索", class: "search-btn" %>
<% end %>
<div class="contents row">
  <% @enigmas.each do |enigma| %>
    <%= render partial: "enigma", locals: { enigma: enigma } %>
  <% end %>
</div>

app/views/enigmas/show.html.erb
<div class="contents row">
  <div class="content_post" style="background-image: url(<%= @enigma.image %>);">
    <% if user_signed_in? && current_user.id == @enigma.user_id %>
      <div class="more">
        <span><%= image_tag 'arrow_top.png' %></span>
        <ul class="more_list">
          <li>
            <%= link_to '編集', edit_enigma_path(@enigma.id), method: :get %>
          </li>
          <li>
            <%= link_to '削除', enigma_path(@enigma.id), method: :delete %>
          </li>
        </ul>
      </div>
    <% end %>
    <p><%= @enigma.text %></p>
    <span class="name">
      <a href="/users/<%= @enigma.user.id %>">
        <span>投稿者</span><%= @enigma.user.nickname %>
      </a>
    </span>
  </div>
  <div class="container">
    <% if user_signed_in? %>
      <%= form_with(model: [@enigma, @comment], local: true) do |form| %>
        <%= form.text_area :text, placeholder: "コメントする", rows: "2" %>
        <%= form.submit "SEND" %>
      <% end %>
    <% else %>
      <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p>
      </strong>
    <% end %>
    <div class="comments">
      <h4>＜コメント一覧＞</h4>
      <% @comments.each do |comment| %>
        <p>
          <strong><%= link_to comment.user.nickname, "/users/#{comment.user_id}" %>：</strong>
          <%= comment.text %>
        </p>
      <% end %>
    </div>
  </div>
</div>

app/views/enigmas/update.html.erb
<div class="contents row">
  <div class="success">
    <h3>更新が完了しました。</h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Enigma0</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="header">
      <div class="header__bar row">
        <h1 class="grid-6"><a href="/">Enigma</a></h1>
        <% if user_signed_in? %>
          <div class="user_nav grid-6">
            <span><%= current_user.nickname %>
              <ul class="user__info">
                <li>
                  <%= link_to "マイページ", "/users/#{current_user.id}" %>
                  <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
                </li>
              </ul>
            </span>
            <%= link_to "エンコード", new_enigma_path, class: "post" %>
          </div>
        <% else %>
          <div class="grid-6">
            <%= link_to "ログイン", new_user_session_path, class: "post" %>
            <%= link_to "新規登録", new_user_registration_path, class: "post" %>
          </div>
        <% end %>
      </div>
    </header>
    <%= yield %>
    <footer>
      <p>
        Copyright enigma 2021.
      </p>
    </footer>
  </body>
</html>

app/views/users/show.html.erb
<div class="contents row">
  <p><%= @nickname %>さんの投稿一覧</p>
  <% @enigmas.each do |enigma| %>
    <%= render partial: "enigmas/enigma", locals: { enigma: enigma } %>
  <% end %>
</div>